version: '3'
services:   
  psirs-frontend-env:
    build:
      context: ./projectmarsfrontend
      dockerfile: Dockerfile-dev
    ports:
      - "4201:4201"
      - "4200:4200"
    container_name: psirs-frontend-env
    volumes:
       - ./projectmarsfrontend:/usr/src/app/projectmarsfrontend
       - /usr/src/app/projectmarsfrontend/node_modules